### ISSUE TITLE
How exactly does the hook happen?

### ISSUE THREAD

**Issue by MrTyton** [nsapa/fanfictionnet_ff_proxy#3]
Hey,

I was wondering how the system here knows when to do a fanficdl selenium hook? Specifically, I've been trying to use it with my [Automated-Fanfic](https://github.com/MrTyton/AutomatedFanfic), and while I can get this to work when I run the fanficfare command manually, when it gets wrapped in the python shell it doesn't appear to work. Do you have any ideas?

Thanks.

**Comment by nsapa** [comment]
Hello,

This [commit](https://github.com/JimmXinu/FanFicFare/commit/2c8e87e85bc4729490ad0aa99d8bf2e14484f2ec) hook nsapa_proxy.py into FanFicFare.

The **get_fetcher** function parse FanFicFare' configuration to find what fetcher to use (nsapa_proxy, cloudscraper, browsercache,  etc...).
When the configuration _use_nsapa_proxy_ is set to True,  **fetchcls** is set to **nsapa_proxy.NSAPA_ProxyFetcher**.

You probably need to pass a config file [here](https://github.com/MrTyton/AutomatedFanfic/blob/a16654503dfcf5b385b160ab561f23b2c51ee8f2/fanficdownload.py#L155)  or [here](https://github.com/MrTyton/AutomatedFanfic/blob/a16654503dfcf5b385b160ab561f23b2c51ee8f2/fanficdownload.py#L165).

Best regards,
Nicolas  SAPA

**Comment by MrTyton** [comment]
The config file in the past has worked by just being in the same directory. But, just to check, I did modify those two lines to explicitly pass in the personal.ini. The config file is set up to disable the cloudflare proxy and to utilize the nsapa proxy.

```
[www.fanfiction.net]
check_next_chapter:true
skip_author_cover:false
user_agent:Mozilla/5.0
continue_on_chapter_error:false
# for use with the workaround
use_nsapa_proxy:true
use_cloudscraper:false
```
```
Exception: Command 'python -m fanficfare.cli -u "C:\$PATH\New Devil of The Gremory House - Master Attlon.epub" --update-cover --non-interactive --config=C:\$PATH\personal.ini' returned non-zero exit status 1.
```

which is kind of making me think that it is a python subprocess thing, hence my question, since it works when I run the command manually - just not when it's wrapped. Not sure what to do, tbh.

Thanks for the help,
-MrTyton

**Comment by MrTyton** [comment]
Closed, it was an env issue.
