### ISSUE TITLE
Cloudflare Nixing Capabilities

### ISSUE THREAD

**Issue by MrTyton** [nsapa/fanfictionnet_ff_proxy#8]
Not sure if there's anything that can be done, but the selenium controlled browser gets stuck on the "Cloudflare is checking your browser" page and refuses to continue on actual story pages.

**Comment by BBandit18** [comment]
NoneType' object is not subscriptable This keeps showing for me

**Comment by nsapa** [comment]
fanfiction.net is currently on the "under-attack" Cloudfare' mode.
The JS challenge they use is able to detect that Chrome is drived by chromedriver.
Nothing I could do without modifing the browser directly (and that' not easy).

**Comment by mcepl** [comment]
And not only this package but almost everything seems to be broken, including for example WebToEpub Firefox extension.
